### ISSUE TITLE
awc.js crashes

### ISSUE THREAD

**Issue by MoritzFago** [ifrost/afterwriting-labs#31]
awc.js crashes
```
node awc.js --source Big-Fish.fountain --pdf
'afterwriting command line interface
www: http://afterwriting.com

/home/$USERNAME/afterwriting-labs-1.2.17/js/client/awrequire.js:54
	var exp = definition(require);
	          ^
TypeError: undefined is not a function
    at global.define (/home/$USERNAME/afterwriting-labs-1.2.17/js/client/awrequire.js:54:12)
    at Object.<anonymous> (/home/$USERNAME/afterwriting-labs-1.2.17/js/utils/textstats.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at Object.require (module.js:384:17)
    at Object.<anonymous> (/home/$USERNAME/afterwriting-labs-1.2.17/js/client/awrequire.js:36:24)
    at /home/$USERNAME/afterwriting-labs-1.2.17/js/utils/pdfmaker.js:6:15
```

**Comment by ifrost** [comment]
Thanks! Check the latest version, should be working now.
