### ISSUE TITLE
Can't build from latest develop branch

### ISSUE THREAD

**Issue by jrschreiber** [ifrost/afterwriting-labs#47]
I'ld like to try out the latest dev version, but building via grunt results in:

```
Running "requirejs:compile" (requirejs) task
Error: ENOENT: no such file or directory, open '/home/username/afterwriting-labs/js/view/settings-panel.js'
In module tree:
    afterwriting-bootstrap
      plugins/settings

{ Error: Error: ENOENT: no such file or directory, open '/home/username/afterwriting-labs/js/view/settings-panel.js'
In module tree:
    afterwriting-bootstrap
      plugins/settings

    at Error (native)

    at /home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:30099:19
    at /home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3081:39
    at /home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3021:25
    at Function.prim.nextTick (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:29929:9)
    at Object.errback (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3020:26)
    at Object.callback (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3006:23)
    at Object.then (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3060:23)
    at build (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:30056:12)
    at runBuild (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:32006:17)
    at Object.execCb (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:1941:33)
  originalError:
   { Error: ENOENT: no such file or directory, open '/home/username/afterwriting-labs/js/view/settings-panel.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.readFile (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3760:27)
       at Object.readFileAsync (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3774:32)
       at Function.require._cacheReadAsync (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:29948:25)
       at /home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:29506:48
       at /home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3063:37
       at /home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:3011:25
       at Function.prim.nextTick (/home/username/afterwriting-labs/node_modules/requirejs/bin/r.js:29929:9)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/username/afterwriting-labs/js/view/settings-panel.js',
     fileName: '/home/username/afterwriting-labs/js/view/settings-panel.js',
     moduleTree: [ 'plugins/settings', 'afterwriting-bootstrap' ] } }
```

Would you please look into it?

**Comment by ifrost** [comment]
Hi John,

`develop` is under heavy refactoring right-now, I'm playing with different ideas to revamp the whole thing and even if it built it wouldn't be fully functional :D 

If you need to make any amendments to the code, or fix bugs, please branch off the `master` branch or use `hotfix` branch.

**Comment by jrschreiber** [comment]
Alright, I thought so.

Looking quite forward to all the changes you are about to push to master from both the `develop` as well as `theme-update` branch! :)
